import globals from "globals"

import { config } from "@workspace/eslint-config/base"

/** @type {import("eslint").Linter.Config} */
export default [
  ...config,
  { languageOptions: { globals: globals.node } },
  {
    // Generated by scripts/build-registry.mjs and scripts/export-21st.mjs.
    ignores: ["registry/**", "public/**", "21st/**"],
  },
]
