import { nextJsConfig } from "@workspace/eslint-config/next-js"

/** @type {import("eslint").Linter.Config} */
export default [
  ...nextJsConfig,
  // Generated by scripts/build-registry.mjs; imports resolve in the host
  // project, not here.
  { ignores: ["registry/**", "public/r/**"] },
]
