import { nextJsConfig } from "@workspace/eslint-config/next-js"

/** @type {import("eslint").Linter.Config} */
export default [
  ...nextJsConfig,
  {
    ignores: [
      // Generated by scripts/build-registry.mjs; imports resolve in the host
      // project, not here.
      "registry/**",
      "public/r/**",
      // Static export output.
      "out/**",
    ],
  },
]
