import { readFile } from "node:fs/promises"
import process from "node:process"
import path from "node:path"

export type RegistryItem = {
  name: string
  title: string
  description?: string
  dependencies?: string[]
  registryDependencies?: string[]
}

export type Registry = {
  name: string
  homepage: string
  items: RegistryItem[]
}

// registry.json is generated by scripts/build-registry.mjs before `next build`.
export async function getRegistry(): Promise<Registry> {
  const file = path.join(process.cwd(), "registry.json")
  return JSON.parse(await readFile(file, "utf8"))
}
